package hibernate01;
// Generated 3 dic. 2019 20:37:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private int deptNo;
     private String dnombre;
     private String loc;
     private Set profesoreses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(int deptNo) {
        this.deptNo = deptNo;
    }
    public Departamentos(int deptNo, String dnombre, String loc, Set profesoreses) {
       this.deptNo = deptNo;
       this.dnombre = dnombre;
       this.loc = loc;
       this.profesoreses = profesoreses;
    }
   
    public int getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(int deptNo) {
        this.deptNo = deptNo;
    }
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public Set getProfesoreses() {
        return this.profesoreses;
    }
    
    public void setProfesoreses(Set profesoreses) {
        this.profesoreses = profesoreses;
    }




}


