package hibernate01;
// Generated 3 dic. 2019 20:37:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Profesores generated by hbm2java
 */
public class Profesores  implements java.io.Serializable {


     private int nrp;
     private Departamentos departamentos;
     private String nombre;
     private String apellidos;
     private String email;
     private Date fechaAlta;

    public Profesores() {
    }

	
    public Profesores(int nrp) {
        this.nrp = nrp;
    }
    public Profesores(int nrp, Departamentos departamentos, String nombre, String apellidos, String email, Date fechaAlta) {
       this.nrp = nrp;
       this.departamentos = departamentos;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.fechaAlta = fechaAlta;
    }
   
    public int getNrp() {
        return this.nrp;
    }
    
    public void setNrp(int nrp) {
        this.nrp = nrp;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }




}


